name: to_do_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # Drift
  drift: ^2.5.0
  path_provider: ^2.0.13
  http: ^1.2.2
  sqlite3: ^1.9.3
  sqlite3_flutter_libs: ^0.5.13

  # Riverpod
  provider: ^6.0.3
  flutter_riverpod: ^2.3.1
  riverpod: ^2.3.1
  riverpod_annotation: ^2.0.1
  collection: ^1.17.0
  equatable: ^2.0.5
  intl: ^0.19.0
  hooks_riverpod: ^2.3.2
  flutter_hooks: ^0.20.5
  path: ^1.8.3
  go_router: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  json_serializable: ^6.2.0
  riverpod_generator: ^2.1.3
  drift_dev: ^2.4.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true